services:
  - type: web
    name: grabit-api
    env: python
    region: frankfurt
    plan: starter
    buildCommand: pip install -r requirements_api.txt
    startCommand: uvicorn grabit_entry:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /api/health
