# Kopia av UNIVERSE i api.py (deploy-branchen) — samma aktier som appen skannar.
UNIVERSE = {
    "AI-infra": ["NVDA","NBIS","CRDO","ALAB","MRVL","AVGO","AMD","SMCI","VRT","DGXX","CRWV","IREN","PENG","AAOI","ANET","CIEN","COHR","LITE","PSTG","NTAP","WDC","STX","CLS","FN","SANM","MPWR","ONTO","TSM","APH","GLW","EQIX","DLR","GDS","VNET","POWL","MOD","AI","HPE","JNPR","UI","PI","AIP","EXTR"],
    "Halvledare": ["HIMX","SKYT","SNPS","NVTS","XFAB.PA","NXPI","MCHP","SWKS","QRVO","ENTG","TER","ASML","LSCC","RMBS","SITM","POWI","SLAB","AMKR","ACLS","AOSL","MTSI","DIOD","ON","WOLF","GFS","UMC","FORM","COHU","UCTT","ICHR","CAMT","NVMI","CRUS","SYNA","MXL","ALGM","INDI","AEIS","KLIC","PLAB","VECO","OLED","SMTC","LFUS","CEVA"],
    "Photonics": ["SIVE.ST","POET","LWLG","VIAV","LPKFF","HLIT","IPGP","MKSI","KOPN"],
    "Quantum": ["IONQ","QUBT","RGTI","QBTS","ARQQ","QMCO","QSI","LAES"],
    "Rare earth": ["USAR","MP","TMC","UAMY","NB","PPTA","IDR","TMQ","CRML","REEMF","NAK","TROX","ATI","MTAL","AREC","ASPI","SGML"],
    "Defense/Drone": ["ONDS","KTOS","AVAV","NOC","GD","LHX","HII","LDOS","BWXT","TXT","AXON","CW","HEI","TDG","RCAT","DRS","UMAC","MRCY","SAIC","CACI","BAH","ESLT","JOBY","ACHR","EH","OSIS","VSEC","DCO","POWW","ATRO","CDRE","VVX","HWM"],
    "Lidar/Phys.AI": ["OUST","LAZR","AEVA","INVZ","MVIS","SERV","SYM","AMBA","RR","AUR","PONY","WRD","CGNX","KSCP","RBOT","ARBE","LIDR"],
    "Nuclear/Energi": ["OKLO","NNE","SMR","UEC","UUUU","VST","DNN","FLNC","CEG","CCJ","LEU","NXE","PEG","EXC","SO","DUK","AEP","D","ETR","NRG","PCG","EIX","XEL","SRE","WEC","ED","GEV","TLN","BW","LTBR","URG","EU","UROY"],
    "Space": ["RKLB","ASTS","RDW","LUNR","SPCE","PL","BKSY","SPIR","IRDM","SATS","GSAT","VSAT","SIDU","VOYG","KULR","MNTS"],
    "Mjukvara": ["NOW","PLTR","ZETA","TTWO","INFQ","ADSK","WDAY","SAP","OKTA","PATH","GTLB","APP","U","RBLX","DOCN","DT","HUBS","MNDY","ASAN","DOCU","TWLO","ZM","DBX","CFLT","ESTC","AKAM","FSLY","BRZE","IOT","TTD","S","DUOL","CVLT","INTA","BASE","FROG","PRGS","NCNO","AMPL"],
    "Fintech/Krypto": ["HOOD","HIVE","SOFI","AFRM","UPST","NU","BILL","TOST","FOUR","FI","GPN","FIS","LC","RKT","MELI","MQ","PAYO","STNE","PAGS","ALLY"],
    "Bio": ["RXRX","VIVO","HIMS","REGN","BIIB","ALNY","BNTX","NBIX","SRPT","INCY","EXEL","UTHR","IONS","ARWR","CRSP","NTLA","BEAM","VKTX","MDGL","HALO","TGTX","NVO","AZN","GSK","NVAX","TEM","RARE","AXSM","RVMD","PACB","TWST","FATE","EDIT","SANA","ABCL","KYMR","RNA","CRNX","DNA","VERA","IOVA"],
    "Mega": ["MSFT","IBM","TSLA","BRK-B","GOOG"],
    "Koppar": ["FCX","HBM","SCCO","TECK","RIO","BHP","VALE","ERO"],
    "Silver/Guld": ["AG","PAAS","GAU","NEM","GOLD","WPM","FNV","AEM","KGC","HMY","EGO","AU","CDE","HL","RGLD","SAND","BTG","SSRM","MAG","EXK","SILV","GATO"],
    "Sverige": ["SUBGEN.ST","SMOL.ST","SHT-B.ST","ACCON.ST","SIVE.ST","OBDU-B.ST","XOM-B.ST","TERRNT-B.ST","VISC.ST","VOLV-B.ST","ERIC-B.ST","SEB-A.ST","SWED-A.ST","INVE-B.ST","ATCO-A.ST","SAND.ST","HEXA-B.ST","EVO.ST","ASSA-B.ST","SHB-A.ST","ABB.ST","ALFA.ST","SKF-B.ST","BOL.ST","TELIA.ST","SAAB-B.ST","NIBE-B.ST","HM-B.ST","SINCH.ST","EQT.ST","ELUX-B.ST","GETI-B.ST","HUSQ-B.ST","KINV-B.ST","SECU-B.ST","SSAB-A.ST","TEL2-B.ST","ESSITY-B.ST","AXFO.ST","LUND-B.ST","SBB-B.ST","BALD-B.ST"],
    "Bevakning": ["IMSR","AIRJ","ORBT","ENAFF","TRT","ABTC","AMPG","KEEL.TO","SOUN","BBAI","APLD","WULF"],
    "Big Tech": ["AAPL","GOOGL","AMZN","META","NFLX","ADBE","CRM","ORCL","CSCO","QCOM","TXN","INTC","INTU","AMAT","MU","LRCX","KLAC","ADI","PANW","CDNS","ARM","DELL","HPQ","ACN","ADP"],
    "SaaS/Moln": ["UBER","ABNB","SHOP","CRWD","DDOG","SNOW","NET","MDB","ZS","TEAM","PYPL","XYZ","VEEV","WIX","BOX","PD","PCTY","PAYC","APPF","BL","FIVN","NICE","GWRE","MANH","TYL","SSNC","WK"],
    "Finans": ["JPM","BAC","WFC","GS","MS","C","V","MA","AXP","BLK","SCHW","SPGI","CB","PGR","COF","USB","PNC","TFC","BK","STT","MET","PRU","AIG","ALL","TRV","AFL","MMC","AON","ICE","CME","NDAQ","MCO","KKR"],
    "Hälsa": ["UNH","JNJ","LLY","PFE","MRK","ABBV","TMO","ABT","AMGN","GILD","MRNA","ISRG","VRTX","BMY","DHR","CVS","ELV","CI","HCA","MDT","SYK","BSX","BDX","ZTS","HUM","CNC","MCK","COR","CAH","IDXX","IQV","A","RMD","DXCM","EW"],
    "Konsument": ["WMT","COST","HD","NKE","MCD","SBUX","KO","PEP","PG","DIS","LOW","TGT","CMG","BKNG","MDLZ","PM","MO","CL","KMB","GIS","KHC","HSY","KDP","STZ","EL","CLX","SYY","KR","DG","DLTR","ROST","TJX","ORLY","AZO"],
    "Industri/Energi": ["XOM","CVX","COP","BA","CAT","GE","HON","LMT","RTX","DE","UPS","UNP","SLB","OXY","NEE","MMM","EMR","ETN","ITW","PH","ROK","PCAR","CMI","CARR","OTIS","JCI","FDX","WM","RSG","GWW","FAST","DOV","AME","ROP"],
    "EV/Clean": ["RIVN","LCID","PLUG","ENPH","FSLR","RUN","CHPT","NIO","XPEV","LI","QS","BE","FCEL","SEDG","NOVA","ARRY","SHLS","ALB","SQM","LAC","BEP","NEP","EOSE","STEM","AMSC","GNRC","CSIQ","JKS","DQ"],
    "Auto/Telekom": ["F","GM","T","VZ","TMUS","STLA","TM","HMC","RACE","HOG","APTV","LEA","BWA","GT","CMCSA","CHTR","LUMN","AMX","VOD"],
    "Krypto-proxy": ["COIN","MSTR","MARA","RIOT","CLSK","BITF","HUT","CIFR","BTBT","CAN","BTDR","CORZ","BMNR","SMLR","BTCS"],
}
